baseURL: "https://magnificent-gaufre-bcc245.netlify.app/"
languageCode: en-us
title: My New Hugo Site
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Welcome Stranger'
    Content: 'This is my blog. Come along on my journey into game development.'
  socialIcons:
    - name: twitter
      url: 'https://www.twitter.com/alexsmusiak/'
    - name: instagram
      url: 'https://www.instagram.com/alexsmusiak/'
  
  cover:
    linkFullImages: true
  
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30